spring.application.name=Finance_Backend

# H2 Database Config
spring.datasource.url=jdbc:h2:mem:financedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# show SQL in console for debugging
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Our JWT secret
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


